# Generated by Django 5.2.17 on 2026-09-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gender", models.CharField(max_length=20)),
                ("part_time_job", models.BooleanField()),
                ("absence_days", models.IntegerField(default=0)),
                ("matematika", models.IntegerField()),
                ("sejarah", models.IntegerField()),
                ("fisika", models.IntegerField()),
                ("kimia", models.IntegerField()),
                ("biologi", models.IntegerField()),
                ("bahasa_inggris", models.IntegerField()),
                ("geografi", models.IntegerField()),
                ("ekstrakurikuler", models.CharField(max_length=100)),
                ("jam_belajar", models.IntegerField()),
                ("aspirasi", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
