# Generated by Django 5.2.17 on 2026-09-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matematika", models.IntegerField()),
                ("informatika", models.IntegerField()),
                ("minat", models.CharField(max_length=100)),
                ("ekstrakurikuler", models.CharField(max_length=100)),
                ("aspirasi", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
